### ISSUE TITLE
Just use `num::Num` as trait for `T` in `kd_tree`

### ISSUE THREAD

**Issue by wucke13** [aeronautical-informatics/openTAWS#20]
The `Tree` struct of KdTree has a lengthy list of trait bounds for `T`. Among them already is `num::traits::Zero`:

https://github.com/aeronautical-informatics/openTAWS/blob/e9d1818b17fdc8e4903760a5bea34f1bc463c089/kd_tree/src/lib.rs#L27

Why not use [`num::Num`](https://docs.rs/num/0.4.0/num/trait.Num.html) as trait bound and be done with it?

**Comment by Steav005** [comment]
Done  
1881590
